version: "3.8"

services:
  backend:
    image: tyutyunov/momo-store-backend:0.0.1
    container_name: momo-store-backend
    restart: always
    ports:
      - "8081:8081"

  frontend:
    environment:
      - VUE_APP_API_URL
    image: tyutyunov/momo-store-frontend:0.0.1
    container_name: momo-store-frontend
    restart: always
    ports:
      - "8080:8080"
