version: "3.8"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-025-75/momo-store/momo-store-backend:${BACKEND_IMAGE_TAG}
    container_name: momo-store-backend
    restart: always
    networks:
      - momo-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-025-75/momo-store/momo-store-frontend:${FRONTEND_IMAGE_TAG}
    container_name: momo-store-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - momo-store

networks:
  momo-store:
    driver: bridge