---
- name: Copy Nginx configuration momo-store.243075.ru.conf
  become: yes
  copy:
    src: ../files/momo-store.243075.ru.conf
    dest: /etc/nginx/sites-available/momo-store.243075.ru.conf

- name: Enable Nginx site momo-store.243075.ru.conf
  become: yes
  file:
    src: /etc/nginx/sites-available/momo-store.243075.ru.conf
    dest: /etc/nginx/sites-enabled/momo-store.243075.ru.conf
    state: link

- name: Nginx reloaded
  become: yes
  service:
    name: nginx
    state: reloaded


- name: Run `docker-compose up`
  become: yes
  become_user: "{{ docker_user }}"
  community.docker.docker_compose_v2:
    project_src: "~/app/"
    services:
      - frontend