---
- name: Copy Nginx configuration nginx-frontend.conf
  become: yes
  copy:
    src: ../files/nginx-frontend.conf
    dest: "/etc/nginx/sites-available/{{ frontend_host }}.conf"

- name: Enable Nginx site nginx-frontend.conf
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ frontend_host }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ frontend_host }}.conf"
    state: link

- name: Obtain SSL certificate
  become: yes
  command: "certbot --nginx -d {{ frontend_host }} --non-interactive --agree-tos --email tyutyunov@braind.agency"

- name: Nginx reloaded
  become: yes
  service:
    name: nginx
    state: reloaded


- name: Run `docker-compose up`
  become: yes
  become_user: "{{ docker_user }}"
  community.docker.docker_compose_v2:
    project_src: "~/app/"
    services:
      - frontend