---
- name: Copy Nginx configuration nginx-frontend.conf
  become: true
  ansible.builtin.copy:
    src: nginx-frontend.conf
    dest: "/etc/nginx/sites-available/{{ frontend_host }}.conf"
    mode: "644"

- name: Enable Nginx site nginx-frontend.conf
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ frontend_host }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ frontend_host }}.conf"
    state: link

- name: Obtain SSL certificate
  become: true
  ansible.builtin.command: "certbot --nginx -d {{ frontend_host }} --non-interactive --agree-tos --email tyutyunov@braind.agency"
  args:
    creates: "/etc/letsencrypt/live/{{ frontend_host }}"

- name: Nginx reloaded
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded


- name: Run `docker-compose up`
  become: true
  become_user: "{{ docker_user }}"
  community.docker.docker_compose_v2:
    project_src: "~/app/"
    services:
      - frontend
