---

- name: Update web image tag in .env file
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.lineinfile:
    path: "~/app/.env"
    regexp: '^BACKEND_IMAGE_TAG='
    line: "BACKEND_IMAGE_TAG={{ backend_image_tag }}"
    create: true
    mode: "644"

- name: Run `docker-compose up`
  become: true
  become_user: "{{ docker_user }}"
  community.docker.docker_compose_v2:
    project_src: "~/app/"
    services:
      - backend
