---

- name: Copy Nginx configuration api.momo-store.243075.ru.conf
  become: yes
  copy:
    src: ../files/api.momo-store.243075.ru.conf
    dest: /etc/nginx/sites-available/api.momo-store.243075.ru.conf

- name: Enable Nginx site api.momo-store.243075.ru.conf
  become: yes
  file:
    src: /etc/nginx/sites-available/api.momo-store.243075.ru.conf
    dest: /etc/nginx/sites-enabled/api.momo-store.243075.ru.conf
    state: link

- name: Nginx reloaded
  become: yes
  service:
    name: nginx
    state: reloaded

- name: Run `docker-compose up`
  become: yes
  become_user: "{{ docker_user }}"
  community.docker.docker_compose_v2:
    project_src: "~/app/"
    services:
      - backend
